export type SkillCategory = "Accessibility" | "UI Architecture" | "Performance" | "Testing" | "Interaction";
export type SkillLevel = "Foundational" | "Practical" | "Advanced";

export type FrontendSkill = {
  id: string;
  slug: string;
  title: string;
  category: SkillCategory;
  level: SkillLevel;
  summary: string;
  prompt: string;
  tags: string[];
  checks: string[];
};

export const skills: FrontendSkill[] = [
  { id: "skill_accessible_components", slug: "accessible-components", title: "Accessible components", category: "Accessibility", level: "Foundational", summary: "Build interface primitives that work with keyboards, screen readers, and touch.", prompt: "You are an accessibility-minded frontend engineer. Build semantic components with labels, focus states, keyboard behavior, and clear status announcements. Explain the decisions and identify any remaining WCAG risks.", tags: ["wcag", "semantics", "focus"], checks: ["Interactive elements are keyboard reachable", "Names and roles are exposed", "Focus is visible and not trapped accidentally"] },
  { id: "skill_semantic_html", slug: "semantic-html", title: "Semantic HTML", category: "Accessibility", level: "Foundational", summary: "Choose HTML elements that communicate structure before adding ARIA.", prompt: "Review the requested interface and use the most meaningful native HTML elements first. Add ARIA only where native semantics do not express the behavior. Call out heading, landmark, and form-structure decisions.", tags: ["html", "landmarks", "aria"], checks: ["One clear page heading exists", "Landmarks describe page regions", "Buttons and links are not substituted for each other"] },
  { id: "skill_keyboard_navigation", slug: "keyboard-navigation", title: "Keyboard navigation", category: "Accessibility", level: "Practical", summary: "Design predictable tab order, shortcuts, escape paths, and focus restoration.", prompt: "Implement and test keyboard navigation for this flow. Define tab order, activation keys, escape behavior, focus restoration, and any shortcut conflicts. Keep shortcuts discoverable and optional.", tags: ["keyboard", "focus", "shortcuts"], checks: ["Tab order follows visual order", "Escape closes temporary UI", "Focus returns to the invoking control"] },
  { id: "skill_responsive_layouts", slug: "responsive-layouts", title: "Responsive layouts", category: "UI Architecture", level: "Foundational", summary: "Turn a desktop composition into a resilient small-screen experience.", prompt: "Design this layout from the smallest useful viewport upward. Define the layout constraints, breakpoints, content priorities, and touch targets. Avoid hiding essential functionality on mobile.", tags: ["responsive", "mobile", "css"], checks: ["No horizontal overflow at narrow widths", "Touch targets are comfortable", "Content order remains logical"] },
  { id: "skill_design_tokens", slug: "design-tokens", title: "Design tokens", category: "UI Architecture", level: "Practical", summary: "Create a compact, reusable visual language instead of one-off styling.", prompt: "Extract color, type, spacing, radius, elevation, and motion decisions into named tokens. Explain how the tokens support consistency and theming without over-abstracting the component API.", tags: ["tokens", "theming", "css"], checks: ["Repeated values have a clear token", "Contrast is checked for text", "Tokens have semantic names"] },
  { id: "skill_component_boundaries", slug: "component-boundaries", title: "Component boundaries", category: "UI Architecture", level: "Advanced", summary: "Split a growing UI around behavior and ownership, not arbitrary file size.", prompt: "Propose component boundaries for this feature. For each boundary, state its responsibility, owned state, public props, and test seam. Prefer composition over a large prop matrix.", tags: ["architecture", "react", "composition"], checks: ["State has one clear owner", "Public props express intent", "Repeated patterns are composed"] },
  { id: "skill_performance_budget", slug: "performance-budget", title: "Performance budget", category: "Performance", level: "Practical", summary: "Keep interaction, JavaScript, image, and layout costs visible from the start.", prompt: "Set a practical performance budget for this page. Identify the largest likely costs, loading strategy, rendering risks, and a measurement plan. Do not claim an optimization without a metric.", tags: ["web-vitals", "bundle", "loading"], checks: ["Critical content has a loading plan", "Heavy work is deferred when possible", "A measurable budget is written down"] },
  { id: "skill_optimized_images", slug: "optimized-images", title: "Optimized images", category: "Performance", level: "Foundational", summary: "Use responsive formats, dimensions, and loading behavior that respect the page budget.", prompt: "Plan image usage for this interface. Specify dimensions, responsive sources, format choices, alt text, loading priority, and a fallback for slow connections.", tags: ["images", "lcp", "alt-text"], checks: ["Images reserve their layout space", "Decorative images have empty alt", "Below-fold images do not block the first view"] },
  { id: "skill_visual_regression", slug: "visual-regression", title: "Visual regression checks", category: "Testing", level: "Advanced", summary: "Turn important visual contracts into repeatable review points.", prompt: "Define visual regression coverage for this feature. Pick stable viewports and states, identify intentional dynamic regions, and describe what should fail loudly when the visual contract changes.", tags: ["screenshots", "testing", "ui"], checks: ["Critical states have fixtures", "Dynamic content is controlled", "Review failures include a semantic explanation"] },
  { id: "skill_interaction_tests", slug: "interaction-tests", title: "Interaction tests", category: "Testing", level: "Practical", summary: "Test the user journey and the meaningful result instead of implementation details.", prompt: "Write a focused interaction test plan for this flow. Cover the happy path, keyboard path, loading state, failure state, and one boundary case. Assert user-visible outcomes.", tags: ["e2e", "testing", "flows"], checks: ["Tests start from user intent", "Async states are awaited", "Failure behavior is asserted"] },
  { id: "skill_error_states", slug: "error-states", title: "Error states", category: "Interaction", level: "Practical", summary: "Make failed requests, invalid input, and unavailable actions understandable.", prompt: "Design the error model for this feature. Distinguish validation, permission, network, and unexpected failures. Provide recovery actions and preserve user-entered work where safe.", tags: ["errors", "forms", "recovery"], checks: ["Errors name the failed action", "Recovery is possible", "Unexpected failures are observable"] },
  { id: "skill_reduced_motion", slug: "reduced-motion", title: "Reduced motion", category: "Interaction", level: "Foundational", summary: "Make motion expressive without making the interface uncomfortable or unusable.", prompt: "Add motion only where it communicates state or hierarchy. Define a reduced-motion alternative, avoid layout-jumping transitions, and keep essential feedback available without animation.", tags: ["motion", "css", "preferences"], checks: ["prefers-reduced-motion is respected", "Motion is not required to understand state", "Focus and feedback remain visible"] },
  { id: "skill_dialog_focus", slug: "dialog-focus", title: "Dialog focus", category: "Accessibility", level: "Practical", summary: "Make modal workflows announce themselves and return focus predictably.", prompt: "Implement dialog focus management with a clear accessible name, an intentional initial focus target, Escape behavior, and focus restoration to the trigger.", tags: ["dialog", "focus", "aria"], checks: ["Focus moves into the dialog", "Escape closes the dialog", "Focus returns to the trigger"] },
  { id: "skill_skip_links", slug: "skip-links", title: "Skip links", category: "Accessibility", level: "Foundational", summary: "Give keyboard users a fast path past repeated navigation.", prompt: "Add a visible-on-focus skip link that targets the page's main content. Make the target focusable without changing the visual layout and verify it works across routes.", tags: ["keyboard", "navigation", "landmarks"], checks: ["Skip link appears on focus", "Target is a real main landmark", "Focus lands on meaningful content"] },
  { id: "skill_form_errors", slug: "Form error summaries", title: "Form error summaries", category: "Accessibility", level: "Practical", summary: "Help users find and recover from multiple invalid fields.", prompt: "Design a form error summary that is announced at the right time, links to invalid fields, preserves entered values, and explains how to recover without blame.", tags: ["forms", "errors", "screen-readers"], checks: ["Errors are associated with fields", "Summary links move focus correctly", "Entered values are preserved"] },
  { id: "skill_compound_components", slug: "compound-components", title: "Compound components", category: "UI Architecture", level: "Advanced", summary: "Compose related UI pieces around shared behavior without prop sprawl.", prompt: "Design a compound component API for this feature. Keep ownership of shared state clear, expose accessible relationships, and show a default composition plus an escape hatch.", tags: ["react", "composition", "api-design"], checks: ["Shared state has one owner", "Composition stays readable", "Invalid combinations fail clearly"] },
  { id: "skill_url_state", slug: "url-state", title: "URL state", category: "UI Architecture", level: "Practical", summary: "Make filters, tabs, and views linkable and restorable.", prompt: "Move shareable view state into the URL with stable parameter names, sensible defaults, and back-button behavior. Keep ephemeral input state local.", tags: ["routing", "filters", "state"], checks: ["A copied URL restores the view", "Defaults are stable", "Back and forward remain useful"] },
  { id: "skill_container_queries", slug: "container-queries", title: "Container queries", category: "UI Architecture", level: "Advanced", summary: "Let components respond to their actual space instead of the viewport alone.", prompt: "Use container queries where component composition changes available space. Define the container boundary, preserve readable fallback styles, and avoid breakpoint-only assumptions.", tags: ["css", "responsive", "layout"], checks: ["Component responds inside different shells", "Fallback styles work without queries", "No layout overflow is introduced"] },
  { id: "skill_route_splitting", slug: "route-splitting", title: "Route splitting", category: "Performance", level: "Practical", summary: "Keep first-load JavaScript focused on the route the user opened.", prompt: "Identify route-specific code that can load later. Set a splitting boundary, preserve loading and error states, and explain how you would measure the bundle change.", tags: ["bundle", "loading", "routes"], checks: ["Critical route code stays available", "Deferred code has a fallback", "Bundle impact is measurable"] },
  { id: "skill_font_loading", slug: "font-loading", title: "Font loading", category: "Performance", level: "Practical", summary: "Choose typography loading behavior that avoids invisible or shifting content.", prompt: "Plan font loading for this interface with a system fallback, explicit display behavior, and a review of layout shift and readability on slow connections.", tags: ["fonts", "cls", "typography"], checks: ["Text remains visible during load", "Fallback metrics are acceptable", "Font requests are intentional"] },
  { id: "skill_virtualized_lists", slug: "virtualized-lists", title: "Virtualized lists", category: "Performance", level: "Advanced", summary: "Render large collections without sacrificing keyboard and scroll behavior.", prompt: "Evaluate whether virtualization is needed, then define item measurement, overscan, focus behavior, and an accessible alternative for the list.", tags: ["lists", "rendering", "scroll"], checks: ["Only necessary rows render", "Keyboard focus remains stable", "Loading and empty states remain visible"] },
  { id: "skill_cache_headers", slug: "cache-headers", title: "Cache headers", category: "Performance", level: "Advanced", summary: "Make asset freshness and revalidation intentional.", prompt: "Classify the resources in this feature by freshness needs. Propose cache and revalidation behavior without caching private or rapidly changing data incorrectly.", tags: ["http", "caching", "freshness"], checks: ["Private data is not shared accidentally", "Immutable assets can be cached", "Freshness expectations are documented"] },
  { id: "skill_failure_path_tests", slug: "failure-path-tests", title: "Failure-path tests", category: "Testing", level: "Practical", summary: "Test what users see when dependencies fail, not just the happy path.", prompt: "Write a failure-path test for this feature covering the failed dependency, visible message, recovery action, and preservation of user work.", tags: ["testing", "errors", "recovery"], checks: ["The dependency failure is controlled", "The user-facing error is asserted", "Recovery is tested"] },
  { id: "skill_accessibility_smoke", slug: "accessibility-smoke", title: "Accessibility smoke tests", category: "Testing", level: "Practical", summary: "Catch basic semantic and keyboard regressions early.", prompt: "Create a small accessibility smoke test for this route. Check the page name, landmark structure, interactive labels, and keyboard access to the primary flow.", tags: ["a11y", "smoke-tests", "ci"], checks: ["Route has a meaningful name", "Primary controls have accessible names", "Keyboard path reaches completion"] },
  { id: "skill_network_mocks", slug: "network-mocks", title: "Network mocks", category: "Testing", level: "Practical", summary: "Make async UI states deterministic and reviewable.", prompt: "Define network mocks for success, slow response, empty data, and failure. Keep the mock contract close to the user journey instead of the implementation detail.", tags: ["testing", "async", "fixtures"], checks: ["Slow states are testable", "Responses match the real contract", "Failure recovery is covered"] },
  { id: "skill_optimistic_updates", slug: "optimistic-updates", title: "Optimistic updates", category: "Interaction", level: "Advanced", summary: "Make safe actions feel immediate while preserving truth when they fail.", prompt: "Use an optimistic update only when rollback is clear and the action is safe. Define pending, success, rollback, and retry states explicitly.", tags: ["async", "latency", "rollback"], checks: ["Pending state is distinguishable", "Rollback restores trustworthy state", "Retry is understandable"] },
  { id: "skill_undo_actions", slug: "undo-actions", title: "Undo actions", category: "Interaction", level: "Practical", summary: "Prefer recoverable actions over unnecessary confirmation dialogs.", prompt: "Design an undo path for this reversible action. Define timing, keyboard access, announcement text, persistence boundaries, and what happens after the undo window closes.", tags: ["recovery", "toast", "actions"], checks: ["Undo is available long enough", "The action is announced", "Expired actions have clear final state"] },
  { id: "skill_command_menus", slug: "command-menus", title: "Command menus", category: "Interaction", level: "Advanced", summary: "Make dense actions discoverable without turning the UI into a maze.", prompt: "Design a command menu with search, grouping, keyboard navigation, shortcuts, and an empty state. Keep destructive actions distinct and confirm context where needed.", tags: ["commands", "keyboard", "search"], checks: ["Commands are searchable", "Keyboard navigation is complete", "Destructive actions are distinguishable"] },
  { id: "skill_progressive_disclosure", slug: "progressive-disclosure", title: "Progressive disclosure", category: "Interaction", level: "Foundational", summary: "Reveal complexity when it becomes useful instead of hiding core actions.", prompt: "Reduce cognitive load by staging secondary detail behind clear controls. Keep primary actions visible, preserve context, and make expanded state shareable where appropriate.", tags: ["hierarchy", "details", "ux"], checks: ["Primary action stays visible", "Hidden detail has a clear trigger", "Expanded state is understandable"] },
  { id: "skill_empty_states", slug: "empty-states", title: "Empty states", category: "Interaction", level: "Foundational", summary: "Turn a blank screen into a clear next step without inventing user data.", prompt: "Design an honest empty state that explains what is missing, why the area is empty, and what the user can do next. Keep sample, cached, and live data clearly distinguished.", tags: ["empty-state", "content", "onboarding"], checks: ["The empty condition is explained", "A useful next action is available", "No placeholder data is presented as real"] },
];

export const skillCategories = ["All", ...Array.from(new Set(skills.map((skill) => skill.category)))];

export function getSkill(slug: string) {
  return skills.find((skill) => skill.slug === slug);
}

export function filterSkills(query: string, category: string) {
  const normalized = query.trim().toLowerCase();
  return skills.filter((skill) => {
    const matchesCategory = category === "All" || skill.category === category;
    const haystack = [skill.title, skill.summary, skill.category, skill.level, ...skill.tags].join(" ").toLowerCase();
    return matchesCategory && (!normalized || haystack.includes(normalized));
  });
}
